version: '3.8'

services:
  appqe:
    # A imagem será construída a partir do Dockerfile no mesmo diretório
    build: .
    # O nome da imagem a ser criada após o build e usada pelo Swarm
    image: aplicationqe
    # Carrega as variáveis do arquivo .env
    env_file:
      - .env
    networks:
      - traefik-public
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.appqe_web.rule=Host(`api.qualityexcellence.com.br`)"
        - "traefik.http.routers.appqe_web.tls.certresolver=letsencrypt"
        - "traefik.http.routers.appqe_web.entrypoints=websecure"
        - "traefik.http.routers.appqe_web.tls=true"
        - "traefik.http.routers.appqe_web.service=appqe_web"
        - "traefik.http.services.appqe_web.loadbalancer.server.port=8080"

        # --- Adicionado para o middleware ---
        # Define um middleware chamado 'appqe-headers' que adiciona o cabeçalho X-Forwarded-Proto
        - "traefik.http.middlewares.appqe-headers.headers.customrequestheaders.X-Forwarded-Proto=https"
        # Aplica o middleware definido acima a este roteador
        - "traefik.http.routers.appqe_web.middlewares=appqe-headers"

networks:
  traefik-public:
    external: true
